# Site settings
title: Dogdig
email: ZQCerrun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  dig deeper， see further.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zerrun.github.io/" # the base hostname & protocol for your site
twitter_username: ErrunZq
github_username:  Zerrun

# Build settings
markdown: kramdown
